### ISSUE TITLE
Objects in catalogue cannot be selected when field outlines are overplotted

### ISSUE THREAD

**Issue by lauraferrarese** [lluttrell/NGVS-map-tool#16]
When "applying" a catalogue, if the field outlines or pointings are then displayed, the objects in the catalogue can no longer be selected (e.g. hovering over them does not display any info and the objects cannot be clicked).

**Comment by lluttrell** [comment]
fixed bug. Pointing outlines are now always behind field outlines. Circle markers are now above all other layers.

**Comment by lauraferrarese** [comment]
Hi Richard -- this still doesn't quite work for me: when displaying the field outlines I can click on an object if that object is at the *intersection* of the outlines, but not if it is in the *middle* of a field (weird!). I am attaching two screenshots since it's hard to explain otherwise!
<img width="1440" alt="Screen Shot 2020-08-03 at 4 16 21 PM" src="https://user-images.githubusercontent.com/64501838/89236186-c1bd8f80-d5a4-11ea-9abf-088f0f1579eb.png">
<img width="1440" alt="Screen Shot 2020-08-03 at 4 16 34 PM" src="https://user-images.githubusercontent.com/64501838/89236194-c6824380-d5a4-11ea-8daf-cf54f0d0b1a0.png">

**Comment by lauraferrarese** [comment]
just noticed that the above does not show the cursor. In the first case, I was pointing at an object in the overlap "strip" between fields, in the second, I was pointing at an object in the middle of a field.

**Comment by lluttrell** [comment]
I wasn't able to reproduce this but I think I fixed it? The markers weren't working when the actual polygon lines overlapped the markers. I fixed that issue and they all seem to work for me now. If you you have a chance to test it again let me know the results!

**Comment by lauraferrarese** [comment]
Hi Richard! Can't load the tool today -- it gives this error "Please start the webpack-dev-server first." I'll check again a bit later!

**Comment by lauraferrarese** [comment]
Yes, it works fine now! Thank you!
